/* eslint-disable @typescript-eslint/no-unused-vars */
import { ChainKey, ChainType } from "@/@types";

const NETWORK = {
  MONAD: ".monad-testnet",
  BASE: ".base-mainnet",
  BASE_SEPOLIA: ".base-sepolia",
  ARB: ".arbitrum-mainnet",
  ETHEREUM: "",
};

const quicknodeRpcs = (network: keyof typeof NETWORK) => [
  // `https://app-name${NETWORK[network]}.quiknode.pro/api-key/`,
];

export const CHAINS: ChainType<ChainKey> = {
  MON_T: {
    name: "Monad Testnet",
    chainId: 10143,
    tokenSymbol: "MON",
    rpcUrls: ["https://testnet-rpc.monad.xyz", ...quicknodeRpcs("MONAD")],

    explorerUrl: "https://testnet.monadexplorer.com",
    nativeCurrency: "MON",
    txUrl: "https://testnet.monadexplorer.com/address/",
    disperseCA: "0xd15fE25eD0Dba12fE05e7029C88b10C25e8880E3",
    rateLimitPerS: 15,
  },
  SONENIUM: {
    name: "Sonenium",
    chainId: 1868,
    tokenSymbol: "ETH",
    rpcUrls: ["https://rpc.soneium.org"],
    explorerUrl: "https://soneium.blockscout.com",
    nativeCurrency: "ETH",
    txUrl: "https://soneium.blockscout.com/tx/",
    disperseCA: "",
  },
  VICTION: {
    name: "Viction",
    chainId: 88,
    tokenSymbol: "VIC",
    rpcUrls: ["https://rpc.viction.xyz"],
    explorerUrl: "https://explorer.forma.art",
    nativeCurrency: "VIC",
    txUrl: "https://www.vicscan.xyz/tx/",
    disperseCA: "",
  },
  TIA: {
    name: "Forma (TIA)",
    chainId: 984122,
    tokenSymbol: "TIA",
    rpcUrls: ["https://rpc.forma.art"],
    explorerUrl: "https://explorer.forma.art",
    nativeCurrency: "TIA",
    txUrl: "https://explorer.forma.art/tx/",
    disperseCA: "",
  },
  APE: {
    name: "APECHAIN",
    chainId: 33139,
    tokenSymbol: "APE",
    rpcUrls: ["https://rpc.apechain.com"],
    explorerUrl: "https://apescan.io",
    nativeCurrency: "APE",
    txUrl: "https://apescan.io/tx/",
    disperseCA: "",
  },
  ABSTRACT: {
    name: "ABSTRACT",
    chainId: 2741,
    tokenSymbol: "ETH",
    rpcUrls: ["https://api.mainnet.abs.xyz"],
    explorerUrl: "https://abscan.org",
    nativeCurrency: "ETH",
    txUrl: "https://abscan.org/tx/",
    disperseCA: "",
  },
  BASE: {
    name: "BASE",
    chainId: 8453,
    tokenSymbol: "ETH",
    rpcUrls: ["https://mainnet.base.org", "https://base-rpc.publicnode.com", ...quicknodeRpcs("BASE")],
    explorerUrl: "https://basescan.org",
    nativeCurrency: "ETH",
    txUrl: "https://basescan.org/tx/",
    disperseCA: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  ARBITRUM_ONE: {
    name: "Arbitrum One",
    chainId: 42161,
    tokenSymbol: "ETH",
    rpcUrls: [
      // "https://arb1.lava.build",
      "https://arbitrum.rpc.subquery.network/public",
      ...quicknodeRpcs("ARB"),
    ],
    explorerUrl: "https://arbiscan.io/",
    nativeCurrency: "ETH",
    txUrl: "https://arbiscan.io/tx/",
    disperseCA: "0xd152f549545093347a162dce210e7293f1452150",
  },
  BASE_SEPOLIA: {
    name: "Base Sepolia Testnet",
    chainId: 84532,
    tokenSymbol: "ETH",
    rpcUrls: [
      "https://base-sepolia-rpc.publicnode.com",
      "https://base-sepolia.drpc.org",
      ...quicknodeRpcs("BASE_SEPOLIA"),
    ],
    explorerUrl: "https://sepolia.basescan.org",
    nativeCurrency: "ETH",
    txUrl: "https://sepolia.basescan.org/tx/",
    disperseCA: "",
  },
  MEGA_ETH_TESTNET: {
    name: "Mega ETH Testnet",
    chainId: 6342,
    tokenSymbol: "ETH",
    rpcUrls: ["https://carrot.megaeth.com/rpc"],
    explorerUrl: "https://testnet.megasec.fi",
    nativeCurrency: "ETH",
    txUrl: "https://testnet.megasec.fi/tx/",
    disperseCA: "",
    fullBlockNotAllowed: true,
    rateLimitPerS: 5,
  },
  FLUENT_TESTNET: {
    name: "Fluent Developer Preview",
    chainId: 20993,
    tokenSymbol: "ETH",
    rpcUrls: ["https://rpc.dev.gblend.xyz"],
    explorerUrl: "https://blockscout.dev.gblend.xyz",
    nativeCurrency: "ETH",
    txUrl: "https://blockscout.dev.gblend.xyz/tx/",
    disperseCA: "",
  },
  BERA: {
    name: "Berachain",
    chainId: 80094,
    tokenSymbol: "BERA",
    rpcUrls: ["https://rpc.berachain.com"],
    explorerUrl: "https://beratrail.io",
    nativeCurrency: "BERA",
    txUrl: "https://beratrail.io/tx/",
    disperseCA: "",
  },
  ETHEREUM: {
    name: "Ethereum Mainnet",
    chainId: 1,
    tokenSymbol: "ETH",
    rpcUrls: [
      // "https://eth.llamarpc.com",
      "https://eth.rpc.blxrbdn.com",
      "https://eth-mainnet.public.blastapi.io",
      // "https://eth.drpc.org",
      ...quicknodeRpcs("ETHEREUM"),
    ],
    explorerUrl: "https://etherscan.io",
    nativeCurrency: "ETH",
    txUrl: "https://etherscan.io/tx/",
    disperseCA: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  POLYGON: {
    name: "Polygon Mainnet",
    chainId: 137,
    tokenSymbol: "MATIC",
    rpcUrls: ["https://polygon-rpc.com"],
    explorerUrl: "https://polygonscan.com",
    nativeCurrency: "MATIC",
    txUrl: "https://polygonscan.com/tx/",
    disperseCA: "",
  },
  BSC: {
    name: "BNB Smart Chain",
    chainId: 56,
    tokenSymbol: "BNB",
    rpcUrls: ["https://bsc-dataseed.bnbchain.org", "https://bsc.rpc.blxrbdn.com", "https://binance.llamarpc.com"],
    explorerUrl: "https://bscscan.com",
    nativeCurrency: "BNB",
    txUrl: "https://bscscan.com/tx/",
    disperseCA: "",
  },
  AVALANCHE: {
    name: "Avalanche C-Chain",
    chainId: 43114,
    tokenSymbol: "AVAX",
    rpcUrls: ["https://api.avax.network/ext/bc/C/rpc"],
    explorerUrl: "https://snowtrace.io",
    nativeCurrency: "AVAX",
    txUrl: "https://snowtrace.io/tx/",
    disperseCA: "",
  },
  FANTOM: {
    name: "Fantom Opera",
    chainId: 250,
    tokenSymbol: "FTM",
    rpcUrls: ["https://rpcapi.fantom.network"],
    explorerUrl: "https://ftmscan.com",
    nativeCurrency: "FTM",
    txUrl: "https://ftmscan.com/tx/",
    disperseCA: "",
  },
  OPTIMISM: {
    name: "Optimism",
    chainId: 10,
    tokenSymbol: "ETH",
    rpcUrls: ["https://mainnet.optimism.io"],
    explorerUrl: "https://optimistic.etherscan.io",
    nativeCurrency: "ETH",
    txUrl: "https://optimistic.etherscan.io/tx/",
    disperseCA: "",
  },
  GNOSIS: {
    name: "Gnosis Chain",
    chainId: 100,
    tokenSymbol: "xDai",
    rpcUrls: ["https://rpc.gnosischain.com"],
    explorerUrl: "https://blockscout.com/xdai/mainnet",
    nativeCurrency: "xDai",
    txUrl: "https://blockscout.com/xdai/mainnet/tx/",
    disperseCA: "",
  },
  ZKSYNC: {
    name: "zkSync Era",
    chainId: 324,
    tokenSymbol: "ETH",
    rpcUrls: ["https://mainnet.era.zksync.io"],
    explorerUrl: "https://explorer.zksync.io",
    nativeCurrency: "ETH",
    txUrl: "https://explorer.zksync.io/tx/",
    disperseCA: "",
  },
  LINEA: {
    name: "Linea Mainnet",
    chainId: 59144,
    tokenSymbol: "ETH",
    rpcUrls: ["https://rpc.linea.build"],
    explorerUrl: "https://lineascan.build",
    nativeCurrency: "ETH",
    txUrl: "https://lineascan.build/tx/",
    disperseCA: "",
  },
  SCROLL: {
    name: "Scroll Mainnet",
    chainId: 534352,
    tokenSymbol: "ETH",
    rpcUrls: ["https://rpc.scroll.io"],
    explorerUrl: "https://scrollscan.com",
    nativeCurrency: "ETH",
    txUrl: "https://scrollscan.com/tx/",
    disperseCA: "",
  },
  ETHEREUM_SEPOLIA: {
    name: "Ethereum Sepolia Testnet",
    chainId: 11155111,
    tokenSymbol: "ETH",
    rpcUrls: ["https://1rpc.io/sepolia"],
    explorerUrl: "https://sepolia.etherscan.io",
    nativeCurrency: "ETH",
    txUrl: "https://sepolia.etherscan.io/tx/",
    disperseCA: "",
  },
  SOMNIA_TESTNET: {
    name: "Somnia testnet",
    chainId: 50312,
    tokenSymbol: "STT",
    rpcUrls: ["https://dream-rpc.somnia.network"],
    explorerUrl: "http://shannon-explorer.somnia.network",
    nativeCurrency: "STT",
    txUrl: "http://shannon-explorer.somnia.network",
    disperseCA: "",
  },
};
